texto = """
APARTAMENTO EXECUTIVO-SINGLE
VALOR MENSAL: R$ 1800,00 REAIS SEM CAFÉ DA MANHÃ.
VALOR MENSAL: 2100,00 REAIS COM CAFÉ DA MANHÃ
APARTAMENTO DUPLO/CASAL
VALOR MENSAL: R$ 2300,00 SEM CAFÉ DA MANHÃ
VALOR MENSAL: R$ 3000,00 COM CAFÉ DA MANHÃ
INCLUSO: TV A CABO, FRIGOBAR, INTERNET, TELEFONE, AR CONDICIONADO, ROUPA DE CAMA E BANHO, LIMPEZA, GARAGEM, NAS ÁREAS SOCIAIS PISCINA TÉRMICA, SAUNA SECA E ÚMIDA, SALA DE JOGOS E EXERCÍCIOS.
LIMPEZA DO APARTAMENTO DUAS (2) VEZES POR SEMANA.
TROCA DE ROUPA DE BANHO DUAS (2) VEZES POR SEMANA.
TROCA DA ROUPA DE CAMA UMA (01) VEZ POR SEMANA.
PAGAMENTO ANTECIPADO.
OBS: APARTAMENTO SUPERIOR APLICAR O ACRÉSCIMO DE 15% NAS TARIFAS EXECUTIVAS."""

print(texto)