# -*- coding: utf-8 -*-
"""criarArquivo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dWbKwU3A9JvHXghd9kjTkEnw8EFoNz2i
"""

def criar_arquivo(nome):
    '''

    @param nome: Deve Passar o nome do arquivo
    @return: Cria um arquivo txt com o nome escolhido

    '''
    try:
        arquivo = nome
        arquivo = open(f"{arquivo}.txt","r+")
        arquivo.close()
        if arquivo == FileNotFoundError:
            print("Arquivo não encontrado")
    except FileNotFoundError:
            arquivo = open(f"{arquivo}.txt", "w+")
            print("Arquivo criado com sucesso")
            arquivo.close()


#Exemplo de uso da Função

#Programa principal
#arquivo = criar_arquivo('nome do arquivo')

#arquivo = open("MeuArquivo.txt", "a", encoding="utf-8")
#print("Minha ópera", file=arquivo) #Salva saída no arquivo
#arquivo.close()